apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  namespace: freshrss-app
  labels:
    io.kompose.service: freshrss-app-storage
  name: data
spec:
  storageClassName: freshrss-app-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
