apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: freshrss-app-storage
  namespace: freshrss-app
provisioner: dobs.csi.digitalocean.com
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate